### ISSUE TITLE
README.md for this repo throws warning when ran through the CLI

### ISSUE THREAD

**Issue by t3dodson** [alanshaw/markdown-pdf#101]
It outputs a pdf but the warnings are concerning.

PS C:\Users\#####\desktop\tmp> markdown-pdf .\README.md
(node) warning: possible EventEmitter memory leak detected. 2 end listeners added. Use emitter.setMaxListeners() to incr
ease limit.
Trace
    at SeriesStream.addListener (events.js:179:15)
    at SeriesStream.Readable.on (_stream_readable.js:671:33)
    at SeriesStream.on (C:\Users\#####\AppData\Roaming\npm\node_modules\markdown-pdf\node_modules\stream-from-to\node_
modules\series-stream\index.js:12:38)
    at SeriesStream.once (events.js:204:8)
    at SeriesStream.Readable.pipe (_stream_readable.js:493:9)
    at SeriesStream.pipe (C:\Users\#####\AppData\Roaming\npm\node_modules\markdown-pdf\node_modules\stream-from-to\nod
e_modules\series-stream\index.js:22:30)
    at C:\Users\#####\AppData\Roaming\npm\node_modules\markdown-pdf\node_modules\stream-from-to\index.js:101:25
    at C:\Users\#####\AppData\Roaming\npm\node_modules\markdown-pdf\node_modules\stream-from-to\node_modules\mkdirp\in
dex.js:48:26
    at FSReqWrap.oncomplete (fs.js:95:15)

**Comment by t3dodson** [comment]
Duplicate of #98
