### ISSUE TITLE
Illegal operation on a directory

### ISSUE THREAD

**Issue by pkaramol** [alanshaw/markdown-pdf#131]
Trying to output the `pdf` to a specific directory with no success:

```
(master)*$ markdown-pdf README.md -o ./pdf
(node) warning: possible EventEmitter memory leak detected. 2 end listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at SeriesStream.addListener (events.js:239:17)
    at SeriesStream.Readable.on (_stream_readable.js:665:33)
    at SeriesStream.on (/usr/local/lib/node_modules/markdown-pdf/node_modules/series-stream/index.js:12:38)
    at SeriesStream.once (events.js:265:8)
    at SeriesStream.Readable.pipe (_stream_readable.js:478:9)
    at SeriesStream.pipe (/usr/local/lib/node_modules/markdown-pdf/node_modules/series-stream/index.js:22:30)
    at /usr/local/lib/node_modules/markdown-pdf/node_modules/stream-from-to/index.js:101:25
    at /usr/local/lib/node_modules/markdown-pdf/node_modules/mkdirp/index.js:47:26
    at FSReqWrap.oncomplete (fs.js:82:15)
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: EISDIR: illegal operation on a directory, open './pdf'
    at Error (native)
```

```
(master)*$ ls -ald pdf
drwxrwxrwx 2 pkara pkara 4096 Oct 23 12:41 pdf
```

**Comment by pkaramol** [comment]
Turns out it needed the entire path to the file:

```
markdown-pdf README.md -o pdf/README.md
```
