### ISSUE TITLE
Command cli: '"file" argument must be a non-empty string'

### ISSUE THREAD

**Issue by glats** [alanshaw/markdown-pdf#142]
Hi: 
When I run ```markdown-pdf -o test.pdf test.md```
Give me this error:
```
(node:7924) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 2 end listeners added. Use emitter.setMaxListeners() to increase limit
child_process.js:383
    throw new TypeError('"file" argument must be a non-empty string');
    ^

TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:383:11)
    at exports.spawn (child_process.js:496:38)
    at Object.exports.execFile (child_process.js:212:15)
    at WriteStream.<anonymous> (/usr/lib/node_modules/markdown-pdf/index.js:117:22)
    at emitNone (events.js:111:20)
    at WriteStream.emit (events.js:208:7)
    at finishMaybe (_stream_writable.js:614:14)
    at afterWrite (_stream_writable.js:465:3)
    at onwrite (_stream_writable.js:455:7)
    at fs.write (fs.js:2192:5)
```
I tried the inverse form: ```markdown-pdf -o test.md test.pdf```
but:
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'prueba.pdf'
```
Thanks for advanced.

**Comment by AlbertoMontalesi** [comment]
Uninstall and reinstall without `--ignore-scripts`. It fixed the problem for me

**Comment by glats** [comment]
Ok. i will try. thnks

**Comment by kendallroth** [comment]
I can confirm that this resolved the issue for me (after it auto-installed PhantomJS).

**Comment by mgrzeszczak** [comment]
What if I can't install without `--ignore-scripts`?

```
Phantom installation failed { Error: EACCES: permission denied, link '/tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1557380191276/phantomjs-2.1.1-linux-x86_64' -> '/usr/lib/node_modules/markdown-pdf/node_modules/phantomjs-prebuilt/lib/phantom'
  errno: -13,
  code: 'EACCES',
  syscall: 'link',
  path: '/tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1557380191276/phantomjs-2.1.1-linux-x86_64',
  dest: '/usr/lib/node_modules/markdown-pdf/node_modules/phantomjs-prebuilt/lib/phantom' } Error: EACCES: permission denied, link '/tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1557380191276/phantomjs-2.1.1-linux-x86_64' -> '/usr/lib/node_modules/markdown-pdf/node_modules/phantomjs-prebuilt/lib/phantom'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
````

**Comment by gtheraud** [comment]
With node v8.16.0, i got the same issue. I guess it's related to https://github.com/nodejs/node/issues/19235

It happens if `opts.phantomPath` is undefined.
I runned ``npm install -g phantomjs-prebuild` and used the `--phantom-path` parameter and it fixed the issue.

**Comment by atempel** [comment]
> With node v8.16.0, i got the same issue. I guess it's related to [nodejs/node#19235](https://github.com/nodejs/node/issues/19235)
> 
> It happens if `opts.phantomPath` is undefined.
> I runned `npm install -g phantomjs-prebuild` and used the `--phantom-path` parameter and it fixed the issue.

Just a correction, the package name I found was `phantomjs-prebuilt` making the line  `npm install -g phantomjs-prebuilt`
