### ISSUE TITLE
The "file" argument must be of type string. Received type object

### ISSUE THREAD

**Issue by gajdaw** [alanshaw/markdown-pdf#159]
Hi,

When I run `markdown-pdf README.md` I get the following error:

```
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at normalizeSpawnArguments (child_process.js:414:3)
    at spawn (child_process.js:553:16)
    at Object.execFile (child_process.js:224:15)
    at WriteStream.<anonymous> (/usr/local/lib/node_modules/markdown-pdf/index.js:117:22)
    at WriteStream.emit (events.js:202:15)
    at finishMaybe (_stream_writable.js:646:14)
    at stream._final (_stream_writable.js:624:5)
    at WriteStream._final (internal/fs/streams.js:270:3)
    at callFinal (_stream_writable.js:617:10)
```

Can anyone suggest any solution?

**Comment by Iceblaze9527** [comment]
same question with node 10.15.1 on macOS 10.14.3

**Comment by DOSull** [comment]
I get the same with node 11.10.0 on ubuntu 18.04.2

**Comment by anko** [comment]
Can't repro… :confused: 

This works for me:

```sh
cd $(mktemp -d)
npm i markdown-pdf
echo '# hi' > README.md
./node_modules/.bin/markdown-pdf README.md
```

Also works with markdown-pdf globally installed.

Version deets:

```sh
$ node -v
v11.10.0
$ ./node_modules/.bin/markdown-pdf --version
9.0.0
$ ./node_modules/.bin/phantomjs --version
2.1.1
```

- - -

>     TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type object
>     [...]
>         at WriteStream.<anonymous> (/usr/local/lib/node_modules/markdown-pdf/index.js:117:22)

That's [here](https://github.com/alanshaw/markdown-pdf/blob/d00e0b9ad87186ac17622fbfaeb3cff2b0e22627/index.js#L117). Looks like `childArgs` contains something nonsensical for some reason, and `childProcess.execFile` throws.

Could one of you add a `console.log(childArgs)` before that line?

**Comment by DOSull** [comment]
Not really my field of expertise, but this is what I got, hope it is helpful. FWIW the markdown-pdf package for Atom works perfectly for me, so don't really need this any more - not sure if it's based on the same codebase. 

```
[ '/home/XXXX/node_modules/markdown-pdf/phantom/render.js',
  '/tmp/tmp-26920Nh0y4Umei4uD.html',
  '/tmp/tmp-269205IAexfFPzKqY.pdf',
  '/home/XXXX/Documents/teaching/GISC-422',
  '/home/XXXX/node_modules/markdown-pdf/runnings.js',
  '/home/XXXX/node_modules/markdown-pdf/css/pdf.css',
  '/home/XXXX/node_modules/markdown-pdf/css/highlight.css',
  'A4',
  'portrait',
  '2cm',
  0,
  10000 ]
```

**Comment by anko** [comment]
@DOSull  Thanks!

It looks fine. It also matches what I get, except mine works. The mystery deepens. I'm out of ideas. :dizzy:

**Comment by y2k2mt** [comment]
I get the same with node 11.11.0.
Reinstall without  ` --ignore-scripts` option and it worked fine.

**Comment by development-1000realities** [comment]
node v10.14.2 
Uninstall and install again without `--ignore-scripts` resolved the issue for me as well.

**Comment by jeremy21212121** [comment]
Thanks for the `--ignore-scripts` tip!

Anyone else experiencing this issue, don't forget the ```-g``` flag in ```npm uninstall -g markdown-pdf``` like I did, because the issue may persist.

After remembering the ```-g``` flag and re-installing markdown-pdf (without ```--ignore-scripts```) it found a missing dependency in PhantomJS and installed it.

Now I'm having a separate error from PhantomJS about libssl and a missing shared object file. On to the next one! It's worth it because I love being able to write reports in markdown and turn them into shiny PDF's for the boss man. Thank you!

**Comment by vlad88sv** [comment]
Hi! no luck on Ubuntu 19.04

Uninstalled with `sudo npm uninstall -g markdown-pdf`
Installed it with: `sudo npm install -g markdown-pdf --ignore-scripts`

Doing: `markdown-pdf doc.md` outputs:

internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^
```

TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at normalizeSpawnArguments (child_process.js:399:3)
    at spawn (child_process.js:532:38)
    at Object.execFile (child_process.js:221:15)
    at WriteStream.<anonymous> (/usr/local/lib/node_modules/markdown-pdf/index.js:117:22)
    at WriteStream.emit (events.js:194:15)
    at finishMaybe (_stream_writable.js:641:14)
    at stream._final (_stream_writable.js:619:5)
    at WriteStream._final (internal/fs/streams.js:263:3)
    at callFinal (_stream_writable.js:612:10)

```

Thank you :)

**Comment by mthird** [comment]
I think they are saying not to include the --ignore-scripts option.  It worked for me when I installed globally with ```npm install -g markdown-pdf```

**Comment by WuglyakBolgoink** [comment]
better to do:

```
sudo npm uninstall -g markdown-pdf
sudo npm install -g markdown-pdf --unsafe-perm
```

**Comment by Eole211** [comment]
> better to do:
> 
> ```
> sudo npm uninstall -g markdown-pdf
> sudo npm install -g markdown-pdf --unsafe-perm
> ```
Thank you, It worked like a charm.

**Comment by la10736** [comment]
Mint 19.1, node 12, installed as local:

```
michele@mdamico-laptop:~/Documenti/Odin$ npx markdown-pdf -o provs.pdf CDMIssues_2019_10_20.md
internal/validators.js:112
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type object
    at validateString (internal/validators.js:112:11)
    at normalizeSpawnArguments (child_process.js:398:3)
    at spawn (child_process.js:534:16)
    at Object.execFile (child_process.js:224:17)
    at WriteStream.<anonymous> (/home/michele/node_modules/markdown-pdf/index.js:117:22)
    at WriteStream.emit (events.js:215:7)
    at finishMaybe (_stream_writable.js:656:14)
    at _stream_writable.js:634:5
    at WriteStream._final (internal/fs/streams.js:279:3)
    at callFinal (_stream_writable.js:627:10)
```

**Comment by AuspeXeu** [comment]
Windows 10, node 12, installed globally
```
/desktop$ markdown-pdf ./sauerkraut.md -o test.pdf
internal/validators.js:112
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type object
    at validateString (internal/validators.js:112:11)
    at normalizeSpawnArguments (child_process.js:398:3)
    at spawn (child_process.js:534:16)
    at Object.execFile (child_process.js:224:17)
    at WriteStream.<anonymous> (/usr/local/lib/node_modules/markdown-pdf/index.js:117:22)
    at WriteStream.emit (events.js:214:15)
    at finishMaybe (_stream_writable.js:647:14)
    at _stream_writable.js:625:5
    at WriteStream._final (internal/fs/streams.js:276:3)
    at callFinal (_stream_writable.js:618:10)
```

**Comment by kanchantyagi8** [comment]
I am also facing the same issue, Node-12, window 10

**Comment by rogerclarkmelbourne** [comment]
I think the install instructions need to be changed.  I had the same issue on Windows 7, until I uninstalled and then re-installed without the --ignore-scripts  
Perhaps this is a Windows specific problem, in which case there should be Windows specific install instructions

**Comment by dcollins42** [comment]
This is happening to me on Ubuntu 20.04 LTS. I tried the following.

```
sudo npm uninstall -g markdown-pdf
sudo npm install -g markdown-pdf
```
I originally installed using `sudo npm install -g markdown-pdf --ignore-scripts`

That did not make any difference.

**Comment by J-Ridgwell** [comment]
> better to do:
> 
> ```
> sudo npm uninstall -g markdown-pdf
> sudo npm install -g markdown-pdf --unsafe-perm
> ```

This worked for me as well. Trying the above solution did not work

**Comment by kennyifraser** [comment]
> sudo npm uninstall -g markdown-pdf
> sudo npm install -g markdown-pdf --unsafe-perm

After error with --ignore-scripts, above worked for me on with node 14.15.5 on macOS 11.2.2

**Comment by burlito** [comment]
```
burlak@andrejBackup /t/tmp.HTxHx1aUwc $ cat README.md 
# hi
burlak@andrejBackup /t/tmp.HTxHx1aUwc $ markdown-pdf ./README.md 
node:internal/validators:120
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received null
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:120:11)
    at normalizeSpawnArguments (node:child_process:505:3)
    at spawn (node:child_process:693:13)
    at Object.execFile (node:child_process:327:17)
    at WriteStream.<anonymous> (/usr/local/lib/node_modules/markdown-pdf/index.js:117:22)
    at WriteStream.emit (node:events:532:35)
    at finish (node:internal/streams/writable:754:10)
    at finishMaybe (node:internal/streams/writable:739:9)
    at afterWrite (node:internal/streams/writable:504:3) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

```
$ npm -v markdown-pdf
8.3.1
```


I have working reproducer at home, and I'm glad to provide any information you want.

**Comment by fearedbliss** [comment]
Uninstalling and re-installing without the `--ignore-scripts` fixed it for me as well.

**Comment by cythilya** [comment]
> Uninstalling and re-installing without the `--ignore-scripts` fixed it for me as well.

That works for me. Thanks!

node version: v18.20.2
markdown-pdf version: 10.5.0

**Comment by AlfreddGco** [comment]
This seems to still not be working for me. I'm using docker so it's hard to setup a global install in it. Why do we need to do global? Why is this error happening? Would like to understand a bit more the root cause, not just a fix that magically works...
