### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by isomorphisms** [alanshaw/markdown-pdf#174]
```
$ markdown-pdf cv.md
(node:29779) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 2 end listeners added. Use emitter.setMaxListeners() to increase limit
child_process.js:383
    throw new TypeError('"file" argument must be a non-empty string');
    ^

TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:383:11)
    at exports.spawn (child_process.js:496:38)
    at Object.exports.execFile (child_process.js:212:15)
    at WriteStream.<anonymous> (/usr/lib/node_modules/markdown-pdf/index.js:117:22)
    at emitNone (events.js:111:20)
    at WriteStream.emit (events.js:208:7)
    at finishMaybe (_stream_writable.js:614:14)
    at afterWrite (_stream_writable.js:465:3)
    at onwrite (_stream_writable.js:455:7)
    at fs.write (fs.js:2192:5)
```

**Comment by qngapparat** [comment]
Please refer to https://github.com/alanshaw/markdown-pdf/issues/159.
