### ISSUE TITLE
Couldn’t specify JSON options on command line

### ISSUE THREAD

**Issue by jamietshaw** [alanshaw/markdown-pdf#176]
It took me ages to work out how to get JSON to work on the command line. A quick example in the documentation would be useful. Example:

`markdown-pdf --remarkable-options '{"preset":"full"}' myfile.md`

**Comment by robert-mccarter** [comment]
I agree @jamietshaw 
Unfortunately, that doesn't even work anymore.
`markdown-pdf --remarkable-options '{"breaks": false}' -b 0.5in ./components.md`

produces:
```
internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at normalizeSpawnArguments (child_process.js:411:3)
    at spawn (child_process.js:545:16)
    at Object.execFile (child_process.js:221:15)
    at WriteStream.<anonymous> (C:\Users\Robert\AppData\Roaming\npm\node_modules\markdown-pdf\index.js:117:22)
    at WriteStream.emit (events.js:203:15)
    at finishMaybe (_stream_writable.js:646:14)
    at stream._final (_stream_writable.js:624:5)
    at WriteStream._final (internal/fs/streams.js:268:3)
    at callFinal (_stream_writable.js:617:10)
```

**Comment by Kabouik** [comment]
Thanks a lot. I'm facing the same issue, but I'm still struggling because I want to use an array for the "syntax" option and haven't figured out how to format it yet. Here is what I tried, without success:

```bash
markdown-pdf test.md -o test.pdf --css-path ~/.config/markdown-css-themes/mytheme.css -m '{"syntax":"md.inline.ruler.enable(['sub'])"}'
```

json example for the arrays: https://github.com/jonschlinkert/remarkable#syntax-extensions

**Comment by rikedyp** [comment]
I've been using powershell on Windows. Finally got it to work by escaping double quotes:

```
markdown-pdf -s style.css -z h.css --remarkable-options '{\"breaks\": "true",\"html\":"true"}' .\assessmentB_base.md
```

I wonder if this project is abandonware on the main repo? No updates in some years. It's a shame, because it was very easy to find, install and start using - but the documentation is severely lacking. Maybe somebody will be able to contribute to the npm package with updates in the future, or at the least improve the documentation.
