### ISSUE TITLE
Bug: internal/validators.js:117: throw new ERR_INVALID_ARG_TYPE(name, 'string', value);

### ISSUE THREAD

**Issue by lower-life** [alanshaw/markdown-pdf#187]
Install:
```bash
npm install -g markdown-pdf --ignore-scripts
npm install -g phantomjs-prebuilt --ignore-scripts
```

Environment:
```
$ markdown-pdf -V
10.0.0
$ nodejs -v
v12.16.2
$ npm --version
6.14.4
$ uname -a
Linux 6c9af48b9e2b 4.19.76-linuxkit #1 SMP Fri Apr 3 15:53:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Command:
```bash
markdown-pdf -p $(which phantomjs) -o 1.pdf -f A4 src.md
```

Error Log:
```log
$ markdown-pdf -p $(which phantomjs) -o 1.pdf -f A4 src.md

internal/streams/legacy.js:61
      throw er; // Unhandled stream error in pipe.
      ^

Error: Command failed: /usr/bin/phantomjs /usr/lib/node_modules/markdown-pdf/phantom/render.js /tmp/tmp-403aLvxXCw8fXB7.html /tmp/tmp-403V3QlAdV1NWbw.pdf /work/report /usr/lib/node_modules/markdown-pdf/runnings.js /usr/lib/node_modules/markdown-pdf/css/pdf.css /usr/lib/node_modules/markdown-pdf/css/highlight.css A4 portrait 2cm 0 10000
internal/validators.js:117
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received null
    at validateString (internal/validators.js:117:11)
    at normalizeSpawnArguments (child_process.js:406:3)
    at spawn (child_process.js:542:16)
    at Object.<anonymous> (/usr/lib/node_modules/phantomjs-prebuilt/bin/phantomjs:22:10)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_INVALID_ARG_TYPE'
}

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: '/usr/bin/phantomjs /usr/lib/node_modules/markdown-pdf/phantom/render.js /tmp/tmp-403aLvxXCw8fXB7.html /tmp/tmp-403V3QlAdV1NWbw.pdf /work/report /usr/lib/node_modules/markdown-pdf/runnings.js /usr/lib/node_modules/markdown-pdf/css/pdf.css /usr/lib/node_modules/markdown-pdf/css/highlight.css A4 portrait 2cm 0 10000'
}

```

**Comment by shadycuz** [comment]
Same 

```
shadycuz-> markdown-pdf github_report.md 
internal/validators.js:107
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type object
    at validateString (internal/validators.js:107:11)
    at normalizeSpawnArguments (child_process.js:407:3)
    at spawn (child_process.js:543:16)
    at Object.execFile (child_process.js:231:17)
    at WriteStream.<anonymous> (/home/shadycuz/.nvm/versions/node/v12.1.0/lib/node_modules/markdown-pdf/index.js:117:22)
    at WriteStream.emit (events.js:201:15)
    at finishMaybe (_stream_writable.js:644:14)
    at _stream_writable.js:622:5
    at WriteStream._final (internal/fs/streams.js:267:3)
    at callFinal (_stream_writable.js:615:10)
```

```
shadycuz-> markdown-pdf -V
10.0.0
shadycuz-> node -v
v12.1.0
shadycuz-> npm --version
6.14.2
shadycuz-> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```

**Comment by squall140** [comment]
The Same!!!


root@a758df86e545:/usr/local/tomcat/log/tms# markdown-pdf /usr/local/tomcat/webapps/ROOT/upload/blog/2_202006050127120.md
internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at normalizeSpawnArguments (child_process.js:411:3)
    at spawn (child_process.js:545:16)
    at Object.execFile (child_process.js:221:15)
    at WriteStream.<anonymous> (/usr/local/lib/node_modules/markdown-pdf/index.js:117:22)
    at WriteStream.emit (events.js:203:15)
    at finishMaybe (_stream_writable.js:646:14)
    at stream._final (_stream_writable.js:624:5)
    at WriteStream._final (internal/fs/streams.js:268:3)
    at callFinal (_stream_writable.js:617:10)

**Comment by JamesABaker** [comment]
After installing with `sudo npm install -g markdown-pdf --ignore-scripts` , running `markdown-pdf test.md` yields 
```
internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at normalizeSpawnArguments (child_process.js:411:3)
    at spawn (child_process.js:545:16)
    at Object.execFile (child_process.js:221:15)
    at WriteStream.<anonymous> (/usr/local/lib/node_modules/markdown-pdf/index.js:117:22)
    at WriteStream.emit (events.js:203:15)
    at finishMaybe (_stream_writable.js:646:14)
    at stream._final (_stream_writable.js:624:5)
    at WriteStream._final (internal/fs/streams.js:268:3)
    at callFinal (_stream_writable.js:617:10)
```

---

```
$ markdown-pdf -V
10.0.0
$ npm --version
6.14.4
$ uname -a
Linux machine 5.4.0-33-generic #37-Ubuntu SMP Thu May 21 12:53:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
