### ISSUE TITLE
Doesn't work: `internal/validators.js:125` `TypeError [ERR_INVALID_ARG_TYPE]`

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [alanshaw/markdown-pdf#194]
I'm on Ubuntu 20.04.

I saw this answer: https://superuser.com/a/902150/425838

Tried to install:

```bash
$ npm install -g markdown-pdf
npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gabriel/.npm/_logs/2020-10-08T06_13_24_844Z-debug.log
```

Failed, so I used `sudo`:

It seems to have worked:

```bash
$ sudo npm install -g markdown-pdf
[sudo] password for gabriel: 
npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/local/bin/markdown-pdf -> /usr/local/lib/node_modules/markdown-pdf/bin/markdown-pdf

> phantomjs-prebuilt@2.1.16 install /usr/local/lib/node_modules/markdown-pdf/node_modules/phantomjs-prebuilt
> node install.js
```

I tried to use it. Failed!

```bash
$ markdown-pdf test.md
internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at normalizeSpawnArguments (child_process.js:411:3)
    at spawn (child_process.js:545:16)
    at Object.execFile (child_process.js:221:15)
    at WriteStream.<anonymous> (/usr/local/lib/node_modules/markdown-pdf/index.js:117:22)
    at WriteStream.emit (events.js:203:15)
    at finishMaybe (_stream_writable.js:646:14)
    at stream._final (_stream_writable.js:624:5)
    at WriteStream._final (internal/fs/streams.js:268:3)
    at callFinal (_stream_writable.js:617:10)
```

**Comment by t0stiman** [comment]
project seems to be dead, sadly

**Comment by bruce2233** [comment]
Same problem. Have you resolved?

**Comment by bing-10** [comment]
> Same problem. Have you resolved?

![image](https://user-images.githubusercontent.com/94583069/180761064-9c5ad656-d242-4ef1-9517-2a5f7fd1ec6c.png)

I have encountered the same problem, and I got the output PDF with nothing, which cannot be opened: 
![image](https://user-images.githubusercontent.com/94583069/180761357-86c3df12-52c3-4c05-8fbb-b781cf3d2b11.png)

@alanshaw Could you give us some advice, please?

**Comment by ElectricRCAircraftGuy** [comment]
FYI all: [here's my current workaround to convert markdown to PDF](https://superuser.com/a/1591372/425838):

Summary of that answer: don't use `markdown-pdf` at all. 

Instead:

1. Use the [Markdown Viewer](https://chrome.google.com/webstore/detail/markdown-viewer/ckkdlimhmcjmikdlpkmbgfkaikojcbjk) plugin in Chrome.
2. Use `pandoc`. [See my answer here](https://stackoverflow.com/a/64257218/4561887):
    ```bash
    pandoc -f gfm -t html5 --metadata pagetitle="test.md" --css github.css \
    test.md -o test.pdf
    ```

**Comment by bing-10** [comment]
> FYI all: here's my current workaround to convert markdown to PDF: https://superuser.com/a/1591372/425838

Thank you for the guidance, but I cannot find any practical solutions for this problem in the community you have provided.

**Comment by ElectricRCAircraftGuy** [comment]
@Billyshane 

> Thank you for the guidance, but I cannot find any practical solutions for this problem in the community you have provided.

I've [updated my comment](https://github.com/alanshaw/markdown-pdf/issues/194#issuecomment-1194151327). Does it make more sense now?
