### ISSUE TITLE
自动化部署 build的时候打包不成功

### ISSUE THREAD

**Issue by 17601617393** [alanshaw/markdown-pdf#207]
Started by user hubbledb
Running as SYSTEM
Building in workspace /var/jenkins_home/workspace/xugq_hubble
The recommended git tool is: NONE
using credential 045e429c-fb73-40e1-83af-a2019af031e1
 > git rev-parse --resolve-git-dir /var/jenkins_home/workspace/xugq_hubble/.git # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://gitee.com/xu_guang_qi/markdown_pdf # timeout=10
Fetching upstream changes from https://gitee.com/xu_guang_qi/markdown_pdf
 > git --version # timeout=10
 > git --version # 'git version 2.20.1'
using GIT_ASKPASS to set credentials 
 > git fetch --tags --force --progress -- https://gitee.com/xu_guang_qi/markdown_pdf +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
Checking out Revision 7a3f7fded7b73a60cc4b47c47d1488b06d83d18e (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 7a3f7fded7b73a60cc4b47c47d1488b06d83d18e # timeout=10
Commit message: "测试"
First time build. Skipping changelog.
[xugq_hubble] $ /bin/sh -xe /tmp/jenkins2918791070791567157.sh
+ cnpm install
- 
✔ Installed 0 packages
✔ Linked 0 latest versions
✔ Run 0 scripts
✔ All packages installed (used 4ms(network 2ms), speed 0B/s, json 0(0B), tarball 0B)
[xugq_hubble] $ /bin/sh -xe /tmp/jenkins5443664206728557470.sh
+ node md_pdf.js
Version 9 of Highlight.js has reached EOL and is no longer supported.
Please upgrade or ask whatever dependency you are using to upgrade.
https://github.com/highlightjs/highlight.js/issues/2877
node:events:371
      throw er; // Unhandled 'error' event
      ^

Error: Command failed: /var/jenkins_home/workspace/xugq_hubble/node_modules/_phantomjs-prebuilt@2.1.16@phantomjs-prebuilt/lib/phantom/bin/phantomjs /var/jenkins_home/workspace/xugq_hubble/node_modules/_markdown-pdf@10.0.0@markdown-pdf/phantom/render.js /tmp/tmp-34092X1XdgkWCFqcW.html /tmp/tmp-34092EeEmgT0DUo4c.pdf /var/jenkins_home/workspace/xugq_hubble /var/jenkins_home/workspace/xugq_hubble/node_modules/_markdown-pdf@10.0.0@markdown-pdf/runnings.js /var/jenkins_home/workspace/xugq_hubble/markdown.css /var/jenkins_home/workspace/xugq_hubble/highlight.css A4 portrait 2cm 0 10000
Auto configuration failed
140247515479680:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
140247515479680:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
140247515479680:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
140247515479680:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1067:16)
    at Socket.<anonymous> (node:internal/child_process:453:11)
    at Socket.emit (node:events:394:28)
    at Pipe.<anonymous> (node:net:672:12)
Emitted 'error' event on Stream instance at:
    at Stream.onerror (node:internal/streams/readable:768:14)
    at Stream.emit (node:events:406:35)
    at DestroyableTransform.reemit (/var/jenkins_home/workspace/xugq_hubble/node_modules/_duplexer@0.1.2@duplexer/index.js:85:16)
    at DestroyableTransform.emit (node:events:394:28)
    at /var/jenkins_home/workspace/xugq_hubble/node_modules/_markdown-pdf@10.0.0@markdown-pdf/index.js:120:40
    at ChildProcess.exithandler (node:child_process:404:5)
    at ChildProcess.emit (node:events:394:28)
    [... lines matching original stack trace ...]
    at Socket.emit (node:events:394:28) {
  killed: false,
  code: 1,
  signal: null,
  cmd: '/var/jenkins_home/workspace/xugq_hubble/node_modules/_phantomjs-prebuilt@2.1.16@phantomjs-prebuilt/lib/phantom/bin/phantomjs /var/jenkins_home/workspace/xugq_hubble/node_modules/_markdown-pdf@10.0.0@markdown-pdf/phantom/render.js /tmp/tmp-34092X1XdgkWCFqcW.html /tmp/tmp-34092EeEmgT0DUo4c.pdf /var/jenkins_home/workspace/xugq_hubble /var/jenkins_home/workspace/xugq_hubble/node_modules/_markdown-pdf@10.0.0@markdown-pdf/runnings.js /var/jenkins_home/workspace/xugq_hubble/markdown.css /var/jenkins_home/workspace/xugq_hubble/highlight.css A4 portrait 2cm 0 10000'
}
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by panda2134** [comment]
Translation of title: packaging failed when building in CI/CD.

**Comment by eriklima** [comment]
I have this same error running on my local machine:
- Ubuntu 20.04
- markdown-pdf 11.0.0

Executed command: 
`npx markdown-pdf -o ../documentation.pdf ../README.md`

Result:

> node:events:491
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: Command failed: /mnt/Backup/VisaoGeo/Projetos/VisaoGeo/MapFeedback/Map Feedback Tool/src/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs /mnt/Backup/VisaoGeo/Projetos/VisaoGeo/MapFeedback/Map Feedback Tool/src/node_modules/markdown-pdf/phantom/render.js /tmp/tmp-20897peskhu0GwjZ2.html /tmp/tmp-20897a0T429BnU3h6.pdf /mnt/Backup/VisaoGeo/Projetos/VisaoGeo/MapFeedback/Map Feedback Tool/src /mnt/Backup/VisaoGeo/Projetos/VisaoGeo/MapFeedback/Map Feedback Tool/src/node_modules/markdown-pdf/runnings.js /mnt/Backup/VisaoGeo/Projetos/VisaoGeo/MapFeedback/Map Feedback Tool/src/node_modules/markdown-pdf/css/pdf.css /mnt/Backup/VisaoGeo/Projetos/VisaoGeo/MapFeedback/Map Feedback Tool/src/node_modules/markdown-pdf/css/highlight.css A4 portrait 2cm 0 10000
> Auto configuration failed
> 139681253812160:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libproviders.so): libproviders.so: não é possível abrir arquivo compartilhado: Arquivo ou diretório inexistente
> 139681253812160:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
> 139681253812160:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=providers, path=providers
> 139681253812160:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=providers

> 
>     at ChildProcess.exithandler (node:child_process:412:12)
>     at ChildProcess.emit (node:events:513:28)
>     at maybeClose (node:internal/child_process:1091:16)
>     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
> Emitted 'error' event on Stream instance at:
>     at Stream.onerror (node:internal/streams/readable:785:14)
>     at Stream.emit (node:events:525:35)
>     at DestroyableTransform.reemit (/mnt/Backup/VisaoGeo/Projetos/VisaoGeo/MapFeedback/Map Feedback Tool/src/node_modules/duplexer/index.js:85:16)
>     at DestroyableTransform.emit (node:events:513:28)
>     at /mnt/Backup/VisaoGeo/Projetos/VisaoGeo/MapFeedback/Map Feedback Tool/src/node_modules/markdown-pdf/index.js:120:40
>     at ChildProcess.exithandler (node:child_process:420:5)
>     at ChildProcess.emit (node:events:513:28)
>     at maybeClose (node:internal/child_process:1091:16)
>     at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
>   code: 1,
>   killed: false,
>   signal: null,
>   cmd: '/mnt/Backup/VisaoGeo/Projetos/VisaoGeo/MapFeedback/Map Feedback Tool/src/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs /mnt/Backup/VisaoGeo/Projetos/VisaoGeo/MapFeedback/Map Feedback Tool/src/node_modules/markdown-pdf/phantom/render.js /tmp/tmp-20897peskhu0GwjZ2.html /tmp/tmp-20897a0T429BnU3h6.pdf /mnt/Backup/VisaoGeo/Projetos/VisaoGeo/MapFeedback/Map Feedback Tool/src /mnt/Backup/VisaoGeo/Projetos/VisaoGeo/MapFeedback/Map Feedback Tool/src/node_modules/markdown-pdf/runnings.js /mnt/Backup/VisaoGeo/Projetos/VisaoGeo/MapFeedback/Map Feedback Tool/src/node_modules/markdown-pdf/css/pdf.css /mnt/Backup/VisaoGeo/Projetos/VisaoGeo/MapFeedback/Map Feedback Tool/src/node_modules/markdown-pdf/css/highlight.css A4 portrait 2cm 0 10000'
> }

Can someone help me?

**Comment by xzhangsir** [comment]
Try using the [markdowntopdfjs](https://github.com/xzhangsir/markdowntopdf) toolkit
